# Service - Loadbalancer                
---
apiVersion: v1
kind: Service
metadata:
  name:  "2048-loadbalancer"
spec:
  selector:
    app:  "2048"
  type:  LoadBalancer 
  ports:
  - name:  http
    port:  80
    targetPort:  80